-- smartKnora Phase 1 fix migration
-- Fixes all schema gaps identified during dev environment audit
-- Runs after 000001-000005 in sequence

-- ============================================================
-- 1. qa_messages: add missing sources column (JSONB)
-- ============================================================
ALTER TABLE qa_messages ADD COLUMN IF NOT EXISTS sources JSONB DEFAULT '[]';

-- ============================================================
-- 2. writing_drafts: add missing space_id column
-- ============================================================
ALTER TABLE writing_drafts ADD COLUMN IF NOT EXISTS space_id VARCHAR(36);

-- ============================================================
-- 3. refresh_tokens: add missing device_id and family columns
-- ============================================================
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS device_id VARCHAR(255) DEFAULT '';
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS family VARCHAR(36) DEFAULT '';

-- ============================================================
-- 4. knowledge_spaces: ensure icon and creator_id columns
-- ============================================================
ALTER TABLE knowledge_spaces ADD COLUMN IF NOT EXISTS icon VARCHAR(255);
ALTER TABLE knowledge_spaces ADD COLUMN IF NOT EXISTS creator_id VARCHAR(36);

-- ============================================================
-- 5. document_versions: recreate table (was missing in dev DB)
-- ============================================================
CREATE TABLE IF NOT EXISTS document_versions (
    id          VARCHAR(36)  PRIMARY KEY DEFAULT gen_random_uuid()::text,
    document_id VARCHAR(36)  NOT NULL,
    tenant_id   BIGINT       NOT NULL DEFAULT 0,
    version     INTEGER      NOT NULL,
    file_path   TEXT,
    file_size   BIGINT,
    chunk_count INTEGER,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(36)
);

CREATE INDEX IF NOT EXISTS idx_doc_versions_document_id ON document_versions(document_id);
CREATE INDEX IF NOT EXISTS idx_doc_versions_tenant_id ON document_versions(tenant_id);

-- ============================================================
-- 6. audit_logs: SmartKnora audit log table
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL DEFAULT 1,
    user_id         VARCHAR(36),
    username        VARCHAR(100),
    action          VARCHAR(100) NOT NULL,
    resource        VARCHAR(100),
    resource_id     VARCHAR(64),
    detail          TEXT,
    ip              VARCHAR(50),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_smart_audit_tenant ON audit_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_smart_audit_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_smart_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_smart_audit_created ON audit_logs(created_at);

-- ============================================================
-- 7. chunk_strategies: ensure table exists
-- ============================================================
CREATE TABLE IF NOT EXISTS chunk_strategies (
    id            VARCHAR(36)  PRIMARY KEY DEFAULT gen_random_uuid()::text,
    tenant_id     BIGINT       NOT NULL DEFAULT 1,
    space_id      VARCHAR(36),
    name          VARCHAR(100) NOT NULL,
    strategy_type VARCHAR(50)  NOT NULL DEFAULT 'fixed_size',
    chunk_size    INTEGER      DEFAULT 512,
    chunk_overlap INTEGER      DEFAULT 50,
    split_markers TEXT,
    is_active     BOOLEAN      DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chunk_strategies_tenant ON chunk_strategies(tenant_id);

-- ============================================================
-- 8. space_categories: ensure table exists
-- ============================================================
CREATE TABLE IF NOT EXISTS space_categories (
    id          VARCHAR(36)  PRIMARY KEY DEFAULT gen_random_uuid()::text,
    tenant_id   BIGINT       NOT NULL DEFAULT 1,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_space_categories_tenant ON space_categories(tenant_id);

-- ============================================================
-- 9. Missing RLS policies
-- ============================================================
-- document_versions RLS
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='document_versions') THEN
        ALTER TABLE document_versions ENABLE ROW LEVEL SECURITY;
        IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname='dv_tenant_isolation' AND tablename='document_versions') THEN
            CREATE POLICY dv_tenant_isolation ON document_versions
                USING (tenant_id = COALESCE(current_setting('app.current_tenant_id')::bigint, 0));
        END IF;
    END IF;
END $$;

-- chunk_strategies RLS
ALTER TABLE chunk_strategies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cs_tenant_isolation ON chunk_strategies;
CREATE POLICY cs_tenant_isolation ON chunk_strategies
    USING (tenant_id = COALESCE(current_setting('app.current_tenant_id')::bigint, 0));

-- space_categories RLS
ALTER TABLE space_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sc_tenant_isolation ON space_categories;
CREATE POLICY sc_tenant_isolation ON space_categories
    USING (tenant_id = COALESCE(current_setting('app.current_tenant_id')::bigint, 0));

-- audit_logs RLS
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS al_tenant_isolation ON audit_logs;
CREATE POLICY al_tenant_isolation ON audit_logs
    USING (tenant_id = COALESCE(current_setting('app.current_tenant_id')::bigint, 0));
