<template>
  <SdpSidebarLayout mode="admin"><main class="page"><div class="shell">
    <header><div><p>External Systems</p><h1>第三方集成</h1><span>连接 HR、OA、合同与文档系统，统一管理同步入口。</span></div><SdpButton @click="openCreate">新增连接器</SdpButton></header>
    <SdpNotice v-if="notice" :type="notice.type" :title="notice.text" />
    <form v-if="showForm" class="form" @submit.prevent="save"><div class="form-head"><h2>{{ draft.id?'编辑连接器':'新增连接器' }}</h2><button type="button" @click="showForm=false">关闭</button></div><div class="fields"><label><span>名称</span><input v-model.trim="draft.name" required placeholder="人事系统" /></label><label><span>同步类型</span><select v-model="draft.type"><option value="users">用户</option><option value="departments">部门</option><option value="documents">文档</option></select></label><label class="wide"><span>Base URL</span><input v-model.trim="draft.baseUrl" required placeholder="https://hr.example.com/api" /></label><label><span>认证方式</span><select v-model="draft.authType"><option value="none">无认证</option><option value="bearer">Bearer Token</option><option value="basic">Basic</option></select></label><label><span>认证凭据</span><input v-model="draft.authToken" type="password" :disabled="draft.authType==='none'" :placeholder="draft.authConfigured?'已配置，留空保持不变':''" /></label><label class="wide"><span>同步规则 JSON</span><textarea v-model="draft.syncRule" rows="4" placeholder='{"path":"/users"}' /></label><label class="toggle"><input v-model="draft.enabled" type="checkbox" /><span>启用连接器</span></label></div><div class="actions"><SdpButton :loading="saving" @click="save">保存</SdpButton><SdpButton variant="ghost" @click="showForm=false">取消</SdpButton></div></form>
    <section class="panel"><div class="panel-head"><div><p>Connectors</p><h2>连接器列表</h2></div><SdpButton size="sm" variant="secondary" :loading="loading" @click="load">刷新</SdpButton></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>类型</th><th>服务地址</th><th>认证</th><th>状态</th><th>上次同步</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ item.name }}</strong></td><td>{{ labels[item.type] }}</td><td><code>{{ item.base_url }}</code></td><td>{{ item.auth_type }}{{ item.auth_configured?' · 已配置':'' }}</td><td>{{ item.enabled?'启用':'停用' }}</td><td>{{ formatTime(item.last_sync_at) }}</td><td><div class="row-actions"><SdpButton size="sm" variant="ghost" @click="openEdit(item)">编辑</SdpButton><SdpButton size="sm" variant="secondary" :loading="working===item.id" @click="sync(item)">立即同步</SdpButton><SdpButton size="sm" variant="danger" :loading="working===item.id+'delete'" @click="remove(item)">删除</SdpButton></div></td></tr><tr v-if="!loading&&!items.length"><td colspan="7" class="empty">暂无第三方连接器</td></tr></tbody></table></div></section>
  </div></main></SdpSidebarLayout>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { createThirdPartyIntegration, deleteThirdPartyIntegration, listThirdPartyIntegrations, syncThirdPartyIntegration, updateThirdPartyIntegration, type ThirdPartyIntegration } from '@/api/admin'
import { SdpButton, SdpNotice } from '@/components/design'
import SdpSidebarLayout from '@/layouts/design/SdpSidebarLayout.vue'
const items=ref<ThirdPartyIntegration[]>([]),loading=ref(true),saving=ref(false),showForm=ref(false),working=ref('')
const notice=ref<{type:'success'|'danger';text:string}|null>(null),labels={users:'用户',departments:'部门',documents:'文档'}
const draft=reactive({id:'',name:'',type:'users' as ThirdPartyIntegration['type'],baseUrl:'',authType:'none' as ThirdPartyIntegration['auth_type'],authToken:'',authConfigured:false,enabled:true,syncRule:'{}'})
function reset(){Object.assign(draft,{id:'',name:'',type:'users',baseUrl:'',authType:'none',authToken:'',authConfigured:false,enabled:true,syncRule:'{}'})}
function openCreate(){reset();showForm.value=true}
function openEdit(item:ThirdPartyIntegration){Object.assign(draft,{id:item.id,name:item.name,type:item.type,baseUrl:item.base_url,authType:item.auth_type,authToken:'',authConfigured:item.auth_configured,enabled:item.enabled,syncRule:JSON.stringify(item.sync_rule||{},null,2)});showForm.value=true}
async function load(){loading.value=true;try{items.value=(await listThirdPartyIntegrations()).data.integrations||[]}catch(e){fail(e,'连接器加载失败')}finally{loading.value=false}}
async function save(){let rule:Record<string,unknown>;try{rule=JSON.parse(draft.syncRule||'{}')}catch{notice.value={type:'danger',text:'同步规则必须是有效 JSON'};return}saving.value=true;const payload={name:draft.name,type:draft.type,base_url:draft.baseUrl,auth_type:draft.authType,auth_token:draft.authToken||undefined,enabled:draft.enabled,sync_rule:rule};try{draft.id?await updateThirdPartyIntegration(draft.id,payload):await createThirdPartyIntegration(payload);notice.value={type:'success',text:'连接器已保存'};showForm.value=false;await load()}catch(e){fail(e,'连接器保存失败')}finally{saving.value=false}}
async function sync(item:ThirdPartyIntegration){working.value=item.id;try{const response=await syncThirdPartyIntegration(item.id,item.type);notice.value={type:'success',text:response.data.message}}catch(e){fail(e,'同步任务提交失败')}finally{working.value=''}}
async function remove(item:ThirdPartyIntegration){if(!window.confirm(`确定删除“${item.name}”吗？`))return;working.value=item.id+'delete';try{await deleteThirdPartyIntegration(item.id);await load()}catch(e){fail(e,'连接器删除失败')}finally{working.value=''}}
function formatTime(value?:string|null){return value?new Date(value).toLocaleString('zh-CN'):'尚未同步'}
function fail(error:unknown,fallback:string){const value=error as {response?:{data?:{error?:string}}};notice.value={type:'danger',text:value.response?.data?.error||fallback}}
onMounted(load)
</script>

<style scoped>
.page{min-height:100dvh;background:var(--ink-100);color:var(--ink-900);font-family:var(--font-body)}.shell{display:grid;gap:var(--space-5);max-width:var(--content-max-width);margin:auto;padding:var(--space-8)}header,.panel-head,.form-head,.actions,.row-actions{display:flex;align-items:center}header,.panel-head,.form-head{justify-content:space-between;gap:var(--space-5)}header p,.panel-head p{color:var(--brand-700);font:var(--font-weight-semibold) var(--text-xs)/1 var(--font-mono);letter-spacing:.08em;text-transform:uppercase}h1{margin-top:var(--space-1);font:var(--font-weight-bold) var(--text-4xl)/1.1 var(--font-display)}h2{font-family:var(--font-display)}header span{display:block;margin-top:var(--space-2);color:var(--ink-600)}.form,.panel{padding:var(--space-5);border:1px solid var(--ink-200);border-radius:var(--radius-lg);background:var(--ink-50)}.form-head button{border:0;background:transparent;color:var(--ink-600);cursor:pointer}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-4);margin-top:var(--space-5)}label{display:grid;gap:var(--space-2);font-size:var(--text-sm);font-weight:var(--font-weight-semibold)}label.wide{grid-column:1/-1}.toggle{display:flex;align-items:center}.toggle input{width:auto}input,select,textarea{width:100%;padding:var(--space-3);border:1px solid var(--ink-300);border-radius:var(--radius-sm);background:var(--ink-50);font:inherit}.actions,.row-actions{gap:var(--space-2);margin-top:var(--space-4)}.row-actions{margin-top:0}.table-wrap{overflow:auto;margin-top:var(--space-5)}table{width:100%;border-collapse:collapse}th,td{padding:var(--space-3);border-top:1px solid var(--ink-200);font-size:var(--text-sm);text-align:left;white-space:nowrap}thead th{border-top:0;background:var(--ink-100);color:var(--ink-600);font-size:var(--text-xs)}td code{display:block;max-width:18rem;overflow:hidden;text-overflow:ellipsis}.empty{text-align:center;color:var(--ink-500)}@media(max-width:48rem){.shell{padding:var(--space-5)}header{align-items:flex-start;flex-direction:column}.fields{grid-template-columns:1fr}label.wide{grid-column:auto}}
</style>
